// FrontEnd-Angular/src/app/simulation/components/playerBoard/playerBoard.component.ts
import { Component, Input, OnDestroy, OnInit } from "@angular/core";
import { Store } from '@ngrx/store';
import { AppState } from "../../../store/app.reducer";
import { Subscription} from 'rxjs';
import { BattleshipsState } from "../../../store/features/battleships/battleships.reducer";
import IShip from "../../assets/IShip";


@Component({
  selector: 'app-playerBoard',
  templateUrl: './playerBoard.component.html',
  styleUrls: ['./playerBoard.component.scss']
})
export class PlayerBoardComponent implements OnInit, OnDestroy {

  @Input() playerId: number;

  //State
  playerShips: IShip[] = [];
  playerBoardState: string[] = [];
  storeSubscription: Subscription = null;

  //Variables
  eleven: number[] = [0,1,2,3,4,5,6,7,8,9,10];
  shipsMap: Map<string, IShip> = null;
  shotsMap: Map<string, boolean> = null;

  constructor(private store: Store<AppState>) {}


  CreatePlayerShipsMap = (playerShips: IShip[]): Map<string, IShip> => {

    let shipsMap = new Map<string, IShip>();

    playerShips.forEach((ship: IShip) => {
        ship.gridCoordinates.forEach((gc) => {
            shipsMap.set(gc.x + gc.y, ship);
        })
    });

    return shipsMap;
  }

  CreateShotsMap = (shotsCoordiantes: string[]): Map<string, boolean> => {

    let shotsMap = new Map<string, boolean>();

    shotsCoordiantes.forEach((gc: string) => {
        shotsMap.set(gc, true);
    });

    return shotsMap;
  }

  ReturnShipMapCoordinates = (I: number, D: number): IShip => {

    return this.shipsMap.get(
      String.fromCharCode(I + +'A'.charCodeAt(0) - 1) + D.toLocaleString()
    )
  }

  ReturnShotsMapCoordinates = (I: number, D: number): boolean => {

    return this.shotsMap.get(
      String.fromCharCode(I + +'A'.charCodeAt(0) - 1) + D.toLocaleString()
    )
  }


  ngOnInit(): void {
    //Store
    this.storeSubscription = this.store.select('battleships').subscribe(

      (state: BattleshipsState) => {
        this.playerShips = this.playerId == 0
        ? state.player1Ships
        : state.player2Ships;

        this.playerBoardState = this.playerId == 0
        ? state.player1BoardState
        : state.player2BoardState;

        //CreateMaps
        this.shipsMap = this.CreatePlayerShipsMap(this.playerShips);
        this.shotsMap = this.CreateShotsMap(this.playerBoardState);
      }
    )
  }

  ngOnDestroy(): void {
    //Store
    this.storeSubscription.unsubscribe();
  }
}

<div class='PlayerBoard'>
  <span *ngFor="let i of eleven">
    <span *ngFor="let d of eleven">
      <app-grid
        [X]='i.toLocaleString()'
        [Y]='d.toLocaleString()'
        [ship]='ReturnShipMapCoordinates(i, d)'
        [isHit]='ReturnShotsMapCoordinates(i,d)'
      >
      </app-grid>
    </span>
  </span>
</div>

// FrontEnd/src/pages/Simulation/PlayerBoard/PlayerBoard.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router';
import { useAppSelector } from '../../../redux/hooks';
import IShip from '../assets/IShip';

//Style
import './style.scss';


const PlayerBoard: React.FunctionComponent<{playerId: number}> = ( { playerId } ) => {

    const CreatePlayerShipsMap = (): Map<string, IShip> => {

        let shipsMap = new Map<string, IShip>();
            playerShips.forEach((ship: IShip) => {
            ship.gridCoordinates.forEach((gc) => {
                shipsMap.set(gc.x + gc.y, ship);
            })
        });

        return shipsMap;
    }

    const eleven: number[] = [0,1,2,3,4,5,6,7,8,9,10];
    
    const playerShips = playerId == 0 
    ? useAppSelector(state => state.battleships.player1Ships)
    : useAppSelector(state => state.battleships.player2Ships);

    const playerBoardState = playerId == 0
    ? useAppSelector(state => state.battleships.player1BoardState)
    : useAppSelector(state => state.battleships.player2BoardState);

    let shipsMap = useMemo(() => {
        return CreatePlayerShipsMap()
    }, [])

    return (
        <div className='PlayerBoard'>
            {
                eleven.map((arg1) => {
                    return eleven.map((arg2) => {
                        return <Grid 
                            X={arg1.toLocaleString()} 
                            Y={arg2.toLocaleString()} 
                            ship={
                                shipsMap.get(
                                    String.fromCharCode(arg1 + +'A'.charCodeAt(0) - 1) + (arg2).toLocaleString()
                                )
                            } 
                            isHit={false}
                            key={arg1+arg2*10}
                        />
                    })
                })
            }
        </div>
    )
}

const Grid: React.FunctionComponent<{X: string, Y:string, ship: IShip, isHit: boolean}> = ({X, Y, ship, isHit}) => {

    const renderText = (): string => {

        if (X == '0' && Y == '0') {
            corner = true;
            return ' ';
        }

        if (X == '0') {
            corner = true;
            return Y;
        }

        if (Y == '0') {
            corner = true;
            return String.fromCharCode(+X + +'A'.charCodeAt(0) -1);
        }

        if (ship == null && isHit == true) {
            return 'X';
        }

        if (ship != null && isHit == true) {
            return `[${ship.className[0]}]`
        }

        if (ship != null) {
            return ship.className[0];
        }

        return '?';
    }

    let corner: boolean = false;
    const text = renderText();
    const cn = ship != null ? ship.className[0] : '';

    return(
        <div className={`Grid ${cn} ${corner ? 'GridCorner' : 'a'}`}>
            {text}
        </div>
    )
}

export default PlayerBoard;
