// FrontEnd/src/pages/Simulation/components/SimulationFooter/SimulationFooter.tsx
import React from 'react';
import { useSimulationFooter } from './utils';

//Style
import './style.scss';


const SimulationFooter: React.FunctionComponent = () => {

    const { 
        currentTurn, maxTurn, refreshDelay,
        ReturnToRoot,IncreaseDelay, DecreaseDelay,
        PauseOrResume, isSimulationPause
     } = useSimulationFooter();


    return (
        <div className='SimulationFooter'>
            <div className='TurnContainer'>{`Turn: ${currentTurn} / ${maxTurn}`}</div>
            <button className='SimulationButton' onClick={ReturnToRoot}>Go to Home</button>
            <div className='SpeedControl'>
                <button onClick={DecreaseDelay}>-</button>
                <div title='How long before new turn' className='CurrentDelay'>{refreshDelay}</div>
                <button onClick={IncreaseDelay}>+</button>
            </div>
            
            <button className='SimulationButton' onClick={PauseOrResume}>
                {!isSimulationPause ? 'PAUSE' : 'RESUME'}
            </button>
        </div>
    );
}

export default SimulationFooter

// FrontEnd-Angular/src/app/simulation/components/simulationFooter/simulationFooter.component.ts
import { Component} from "@angular/core";
import { Router } from "@angular/router";
import { Store } from "@ngrx/store";
import { Subscription } from "rxjs";
import { AppState } from "../../../store/app.reducer";
import { BattleshipsState } from "../../../store/features/battleships/battleships.reducer";
import { SetRefreshDelay, SetIsSimulationPause } from "../../../store/features/battleships/battleships.actions";


@Component({
  selector: 'app-simulationFooter',
  templateUrl: './simulationFooter.component.html',
  styleUrls: ['./simulationFooter.component.scss']
})
export class SimulationFooterComponent {

  public GoBackToRoot = () => this.router.navigate(['/']);
  public DecreaseDelay = (): void => {
    if (this.refreshDelay - this.interval >= this.minDelay)
      this.store.dispatch(SetRefreshDelay({prop: this.refreshDelay - this.interval}));
  }
  public IncreaseDelay = (): void => {
    if (this.refreshDelay + this.interval <= this.maxDelay)
      this.store.dispatch(SetRefreshDelay({prop: this.refreshDelay + this.interval}));
  }
  public FormatCurrentTurn = (): string => {

    const maxTurnStringLength = this.maxTurn.toLocaleString().length;
    const currentTurnRawStringLength = this.currentTurnRaw.toLocaleString().length;

    let returnValue: string = '';
    for (let i = 0; i < (maxTurnStringLength - currentTurnRawStringLength); i++)
      returnValue += '0';

    returnValue += this.currentTurnRaw.toLocaleString();

    return returnValue;
  }
  public PauseOrResume = (): void => this.store.dispatch(SetIsSimulationPause({prop: !this.isSimulationPause}));



  //Const
  interval: number = 100;
  minDelay: number = 200;
  maxDelay: number = 2000;

  //State
  currentTurnRaw: number = 0;
  maxTurn: number = 0;
  refreshDelay: number = 0;
  isSimulationPause: boolean = false;
  storeSubscription: Subscription = null;


  ngOnDestory(): void {
    //Store
    this.storeSubscription.unsubscribe();
  }

  ngOnInit(): void {
    //Store
    this.storeSubscription = this.store.select('battleships').subscribe(

      (state: BattleshipsState) => {
        this.currentTurnRaw = state.currentTurn;
        this.maxTurn = state.maxTurns;
        this.refreshDelay = state.refreshDelay;
        this.isSimulationPause = state.isSimulationPause;
      }
    )
  }

  constructor(
    private router: Router,
    private store: Store<AppState>) {}
}

<div class="SimulationFooter">
  <div class='TurnContainer'>Turn: {{FormatCurrentTurn()}} / {{maxTurn}}</div>
  <button class='SimulationButton' (click)='GoBackToRoot()'>Go to Home</button>

  <div class='SpeedControl'>
    <button (click)='DecreaseDelay()'>-</button>
    <div title='How long before new turn' class='CurrentDelay'>{{refreshDelay}}</div>
    <button (click)='IncreaseDelay()'>+</button>
  </div>

  <button class='SimulationButton' (click)='PauseOrResume()'>
    {{!isSimulationPause ? 'PAUSE' : 'RESUME'}}
  </button>
</div>
